// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAij2AmzQev23zn8HWsJS9yHyU_fpFhlvI',
    appId: '1:712830345367:web:f7da75c182f5726ce689d2',
    messagingSenderId: '712830345367',
    projectId: 'rentappfirebase',
    authDomain: 'rentappfirebase.firebaseapp.com',
    storageBucket: 'rentappfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cuckaVeS5Trm1MLR7qWtgCmKji9nlvU',
    appId: '1:712830345367:android:65ad869604bf7f1ee689d2',
    messagingSenderId: '712830345367',
    projectId: 'rentappfirebase',
    storageBucket: 'rentappfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwerhnRwIWBeaiaZr2YKDTpWWcngictz8',
    appId: '1:712830345367:ios:3e8cba30e76e544ce689d2',
    messagingSenderId: '712830345367',
    projectId: 'rentappfirebase',
    storageBucket: 'rentappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwerhnRwIWBeaiaZr2YKDTpWWcngictz8',
    appId: '1:712830345367:ios:3e8cba30e76e544ce689d2',
    messagingSenderId: '712830345367',
    projectId: 'rentappfirebase',
    storageBucket: 'rentappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAij2AmzQev23zn8HWsJS9yHyU_fpFhlvI',
    appId: '1:712830345367:web:6c980547bde3bd47e689d2',
    messagingSenderId: '712830345367',
    projectId: 'rentappfirebase',
    authDomain: 'rentappfirebase.firebaseapp.com',
    storageBucket: 'rentappfirebase.firebasestorage.app',
  );
}
